### ISSUE TITLE
verbose command

### ISSUE THREAD

**Issue by itsvic-dev** [omaemae/bob#4]
proposed output:

```yml
content: {answer}
embed:
  fields:
    - name: I thought you said...
      value: {question.text}
    - name: Originally said by
      value: <@{answer.author}> in <#{question.channel}>, replying to <@{question.author}>
```
